Repository Olympus-Group/athena, pull requests merged in 2024-05, with the labels that each got.

#15 Added file system interface
  .eslintrc.json
  interfaces/reader.ts
Labels: feature

#18 Fixed command line interface
  interfaces/cli.ts
  jest.config.js
  package-lock.json
  package.json
  test/cli.test.ts
Labels: bug, refactoring, testing

#20 Added continuous integration
  .github/workflows/deploy.yml
Labels: feature, testing

#25 Added parser logic
  core/Lexer.ts
  core/Parser.ts
  core/logger/errors.ts
  core/rules/ExampleNode.ts
  core/rules/FieldNode.ts
  core/rules/IsNumberNode.ts
  core/rules/Node.ts
  core/utils/convert.ts
  core/utils/nodes.ts
  core/utils/types.ts
  test/lexer.test.ts
Labels: feature, refactoring

#28 Added complex logging
  core/Lexer.ts
  core/Parser.ts
  core/logger/colors.ts
  core/logger/errors.ts
  core/logger/nodes/IsNumberErrors.ts
  core/rules/FieldNode.ts
  core/rules/IsNumberNode.ts
Labels: enhancement

#32 Fixed examples schemas
  test/static/1-simple.schema
  test/static/2-arrays.schema
Labels: bug

#34 Added project description
  README.md
  interfaces/cli.ts
Labels: documentation, feature

#33 Added entry point
  core/Lexer.ts
  core/logger/errors.ts
  core/rules/FieldNode.ts
  core/rules/Node.ts
  core/token/TokenType.ts
  core/utils/nodes.ts
  core/utils/regexp.ts
  index.ts
Labels: feature, refactoring
